### ISSUE TITLE
About the Clip + FT results

### ISSUE THREAD

**Issue by CCCTong** [LeapLabTHU/DAPrompt#3]
Thanks for your excellent work, but I'm curious about the Clip + FT experimental settings you posted. What data and which part of the parameters do you use for fine-tune ?

**Comment by John-Ge** [comment]
We finetune the image backbone of CLIP. Training data are the same with baselines. We find it is hard for finetuning to achieve better performance. This mayby because the dataset is small for finetuning CLIP.
